### ISSUE TITLE
Please build for node LTS

### ISSUE THREAD

**Issue by murderteeth** [solidity-utilities/abi-to-interface#1]
Hi there, this package could be really useful. Please consider building for the LTS version of node instead of latest. For example, I came across this:
https://github.com/solidity-utilities/abi-to-interface/blob/main/src/lib/parse/ast/index.ts#L22

In that case, array.at() breaks for node less than v16:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

You could also try a polyfill like corejs. Personally, I'd just write it for the LTS.

Thanks for listening!

**Comment by murderteeth** [comment]
HA nm! Was mistaken about current lts version.

**Comment by S0AndS0** [comment]
Yep, checking the [NodeJS -- Downloads](https://nodejs.org/en/download/) page it seems, at the time of writing, the latest LTS version is `16.13.2`


In the future feel free to open a Pull Request if ya find any bugs.


## Development Tips


- Uninstall NPM version

```bash
npm uninstall @solidity-utilities/abi-to-interface
```

- Follow the [Forking](https://github.com/solidity-utilities/abi-to-interface#forking) instructions

- Use `link` NPM command to _install_ development version to currently logged in account

```bash
cd ~/git/hub/solidity-utilities/abi-to-interface

npm link
```

- Modify source code within the `src/` sub-directory

- Use `ts-build`, or `ts-watch`, NPM command to re-build

```bash
cd ~/git/hub/solidity-utilities/abi-to-interface

npm ts-build
```

- Test modifications via `solidity-abi-to-interface` command with some inputs

```bash
solidity-abi-to-interface --abi build/contracts/Account.json\
                          --out contracts/InterfaceAccount.sol
```

- Push changes to your _`<fork>`_ remote and open a Pull/Merge Request if feature/bug-fix is groovy

```bash
git push <fork> main
```
